# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3.4.0
_src_path: gh:epics-containers/ec-services-template
beamline: bl01t
cluster_namespace: local
description: beamline bl01t IOC Instances and Services
git_platform: github.com
github_org: niamhdougan
repo_uri: git@github.com:niamhdougan/bl01t.git
type: beamline
